# Form implementation generated from reading ui file 'nofiledialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(232, 132)
        icon = QtGui.QIcon.fromTheme("dialog-information")
        Dialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoImage = QtWidgets.QLabel(Dialog)
        self.infoImage.setText("")
        self.infoImage.setPixmap(QtGui.QPixmap("Information_icon_with_gradient_background.svg"))
        self.infoImage.setObjectName("infoImage")
        self.horizontalLayout.addWidget(self.infoImage)
        self.infoText = QtWidgets.QLabel(Dialog)
        self.infoText.setObjectName("infoText")
        self.horizontalLayout.addWidget(self.infoText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.okButton = QtWidgets.QDialogButtonBox(Dialog)
        self.okButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.okButton.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okButton.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.okButton.rejected.connect(Dialog.reject) # type: ignore
        self.okButton.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "No APK"))
        self.infoText.setText(_translate("Dialog", "No APK selected."))
